### POST request to add a new patient
POST http://localhost:3003/api/patients
Content-Type: application/json

{
  "name": "John Doe",
  "dateOfBirth": "1990-01-01",
  "ssn": "123-45-6789",
  "gender": "male",
  "occupation": "Software Engineer"
}

###POST request to add a new entry (John McClaine)
POST http://localhost:3003/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "date": "2024-07-10",
  "type": "Hospital",
  "description": "Paciente ingresado por emergencia",
  "specialist": "Dr. Smith",
  "discharge": {
    "date": "2024-07-15",
    "criteria": "Criterios cumplidos"
  }
}
###POST request to add a new entry (John McClaine)
POST http://localhost:3003/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "date": "2019-10-20",
  "specialist": "MD House",
  "type": "HealthCheck",
  "description": "Yearly control visit. Cholesterol levels back to normal.",
  "healthCheckRating": 0
}