GET http://localhost:3003/api/blogs/

###
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBlcHBlcm9uaTgzIiwiaWQiOiI2NjM1MmNjMzY1YjczNzdkMTg0YTc0N2UiLCJpYXQiOjE3MTQ3NjA5MDZ9.f_RH7aSHpopqAEs9Q7KMpWlFpaTIb05SDrj6aH9g7Zw

{
    "title": "Pizzamazing",
    "author": "Johnny Pepperoni",
    "url": "pizza.com",
    "likes": 7
}
###
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNhbnRhcmluYTkzIiwiaWQiOiI2NjNiNGRhN2MzNzM3OTBhY2I4YzE5MmUiLCJpYXQiOjE3MTUxNzIxMzR9.p_ftUnuzqyz0lFN9yU310LgTs-MjoGvn9IigUsVXE28

{
    "title": "Sandwich mixto",
    "author": "Angela",
    "url": "trancheteando.com",
    "likes": 4
}
###

DELETE http://localhost:3003/api/blogs/66292aa0696a9b5ed336b37f HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNhbnRhcmluYTkzIiwiaWQiOiI2NjMzYzc0Yzg5N2UyMWYzNWVkNTBlNTUiLCJpYXQiOjE3MTQ3NjEwNDd9.24UqDx5oDoa6twO88QcEFYfG4d4W4SdqFZpNqQkyBa0
###

PUT http://localhost:3003/api/blogs/66292a9a696a9b5ed336b379 HTTP/1.1
Content-Type: application/json

{

    "title": "Sandwich MUY mixto",
    "author": "Angela",
    "url": "trancheteando.com",
    "likes": 4
}